version: "3.0"

services:
  oracle:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    volumes:
      - .:/code
    environment:
      #admin username :
      #ORACLE_USER: system(default)

      #admin password
      ORACLE_PASSWORD: "oracle"

      # application user
      APP_USER: "test_user"

      # application user's password
      APP_USER_PASSWORD: "test_password"

      # default pluggable database name
      TARGET_PDB: "XEPDB1" #default